server:
#  servlet:
  #    context-path: /client
  port: 8081
  max-http-header-size: 10485760
spring:
  application:
    name: service-client
  main:
    banner-mode=off:eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
logging:
  level:
    org.springframework.cloud.gateway: info
management:
  endpoints:
    web:
      exposure:
        include=*: