server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    enable-self-preservation: false
#    use-read-only-response-cache: false
spring:
  application:
    name: eureka-server

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %class{36}.%M\(%file:%L\) : %msg%n'
